### ISSUE TITLE
Status is WARPING on load

### ISSUE THREAD

**Issue by Lothsahn** [DaggerES/LunaMultiPlayer#16]
You don't start with a subspace, so your ID is -1.  Time warping and stopping will fix the status.

**Comment by Lothsahn** [comment]
Not sure the proper place to assign or grab the current subspace on load, but it seems like you should have a subspace on load, or join the current active subspace...

**Comment by Lothsahn** [comment]
Players should join the latest subspace when they join.  They appear to join at T=0.

**Comment by thempc** [comment]
Only happens with a saved server state, couldn't reproduce this at first but this doesn't seem to happen if you have a new universe (delete / backup old one to see it working correctly.)

**Comment by DaggerES** [comment]
Fixed
