### ISSUE TITLE
Debris cleanup causes NullReferenceExceptions

### ISSUE THREAD

**Issue by Lothsahn** [DaggerES/LunaMultiPlayer#21]
[WRN 15:19:00.150] Vessel Aeris 3A Debris was removed from the game: it was debris cluttering up KSC.
[EXC 15:19:00.154] NullReferenceException
	VPWheelCollider.UpdateVisualWheel ()
	VehiclePhysics.VehicleBase.LateUpdate ()
[EXC 15:19:00.171] NullReferenceException
	VPWheelCollider.GetGroundHit (UnityEngine.WheelHit& hit)
	VehiclePhysics.VehicleBase.CalculateSuspensionTravel (VehiclePhysics.WheelState wheel)
	VehiclePhysics.VehicleBase.FixedUpdate ()
[EXC 15:19:00.181] NullReferenceException
	VPWheelCollider.GetGroundHit (UnityEngine.WheelHit& hit)
	VehiclePhysics.VehicleBase.CalculateSuspensionTravel (VehiclePhysics.WheelState wheel)
	VehiclePhysics.VehicleBase.FixedUpdate ()

**Comment by jrodrigv** [comment]
I think this is a KSP bug. Getting the same error on BDArmory

**Comment by DaggerES** [comment]
No LMP error. KSP bug
