### ISSUE TITLE
If the resolution is reduced, the LMP window can appear offscreen

### ISSUE THREAD

**Issue by Lothsahn** [DaggerES/LunaMultiPlayer#23]
The window should move to within the visible area when joining a game or launching KSP.

**Comment by DaggerES** [comment]
There's no event that is triggered when the resolution is changed. So the only solution to this would be to restart KSP as when the plugin starts the connection screen is always positioned according to the current resolution.

Other solution would be to store the resolution once LMP starts and poll at every frame if the resolution has changed, but I consider this an overkill for something that happens very rarely
