### ISSUE TITLE
Stack trace on disconnect

### ISSUE THREAD

**Issue by Lothsahn** [DaggerES/LunaMultiPlayer#24]
[LOG 10:04:05.696] [LMP]: Disconnected, reason: Connection timed out
[ERR 10:04:05.718] [LMP]: Invalid server list reply msg: System.NullReferenceException: Object reference not set to an instance of an object
  at LunaClient.Network.NetworkServerList.HandleServersList (Lidgren.Network.NetIncomingMessage msg) [0x00026] in C:\shared\kerbal space program\LunaMultiPlayer\Client\Network\NetworkServerList.cs:52 
	UnityEngine.Debug:LogError(Object)
	LunaClient.Network.NetworkServerList:HandleServersList(NetIncomingMessage) (at C:/shared/kerbal space program/LunaMultiPlayer/Client/Network/NetworkServerList.cs:86)
	LunaClient.Network.NetworkReceiver:ReceiveMain() (at C:/shared/kerbal space program/LunaMultiPlayer/Client/Network/NetworkReceiver.cs:56)
	System.Threading.Tasks.ThreadPoolTaskScheduler:TaskExecuteWaitCallback(Object)

**Comment by Lothsahn** [comment]
The error is made more descriptive in my most recent commit.  However, the underlying bug of why the message cannot be deserialized is not resolved.

**Comment by DaggerES** [comment]
Fixed
