### ISSUE TITLE
Random ship explosions occur along with NullReferenceExceptions

### ISSUE THREAD

**Issue by Lothsahn** [DaggerES/LunaMultiPlayer#26]
Here's a snippet of my KSP.log file.  The explosion occurred at 15:11:23 in the log.  After that happens, this error occurs repeatedly in the log file:
[EXC 15:11:24.516] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionStay (UnityEngine.Collision c)

[LOG 15:11:03.367] Camera Mode: FREE
[LOG 15:11:03.579] Camera Mode: ORBITAL
[LOG 15:11:03.757] Camera Mode: CHASE
[LOG 15:11:04.231] Camera Mode: LOCKED
[EXC 15:11:23.558] NullReferenceException: Object reference not set to an instance of an object
	ProtoPartSnapshot.Load (.Vessel vesselRef, Boolean loadAsRootPart)
	ProtoVessel.LoadObjects ()
	Vessel.Load ()
	Vessel.Update ()
[EXC 15:11:23.562] NullReferenceException: Object reference not set to an instance of an object
	Part.GetModuleStartState ()
	Part.ModulesOnStart ()
	Part+<Start>c__Iterator38.MoveNext ()
	UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
[EXC 15:11:23.580] NullReferenceException: Object reference not set to an instance of an object
	ModuleAnimateGeneric.FixedUpdate ()
[EXC 15:11:23.587] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[LOG 15:11:23.597] [LMP]: OVC Hairie Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.604] [LMP]: OVC Camzon Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.612] [LMP]: OVC Iralla Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.619] [LMP]: OVC Julma Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.642] [LMP]: OVC Hairie Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.652] [LMP]: OVC Camzon Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.663] [LMP]: OVC Iralla Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.671] [LMP]: OVC Julma Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.685] [LMP]: OVC Hairie Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.694] [LMP]: OVC Camzon Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.703] [LMP]: OVC Iralla Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.711] [LMP]: OVC Julma Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.728] [LMP]: OVC Hairie Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.736] [LMP]: OVC Camzon Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.743] [LMP]: OVC Iralla Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.750] [LMP]: OVC Julma Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.765] [LMP]: OVC Hairie Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.771] [LMP]: OVC Camzon Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.778] [LMP]: OVC Iralla Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.784] [LMP]: OVC Julma Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.797] [LMP]: OVC Hairie Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.804] [LMP]: OVC Camzon Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.810] [LMP]: OVC Iralla Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.821] [LMP]: OVC Julma Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.834] [LMP]: OVC Hairie Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.841] [LMP]: OVC Camzon Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.847] [LMP]: OVC Iralla Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.853] [LMP]: OVC Julma Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.866] [LMP]: OVC Hairie Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.872] [LMP]: OVC Camzon Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.878] [LMP]: OVC Iralla Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[LOG 15:11:23.885] [LMP]: OVC Julma Kerman belongs to c2e2c642-3b03-43f2-9d5a-3731df447a6a
[EXC 15:11:23.924] NullReferenceException: Object reference not set to an instance of an object
	ModuleAnimateGeneric.FixedUpdate ()
[EXC 15:11:23.959] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.961] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.964] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.966] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.968] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.969] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.971] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.972] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.973] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.974] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.976] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.977] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.979] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.980] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.981] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:23.982] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[LOG 15:11:23.984] [F: 47718]: wingStrake collided into mk3CargoBayM - relative velocity: 42.70987 - impact momentum: 128.1
[LOG 15:11:23.988] wingStrake Exploded!! - blast awesomeness: 0.1
[LOG 15:11:23.992] [wingStrake]: Deactivated
[LOG 15:11:24.000] [F: 47718]: airlinerCtrlSrf collided into airlinerMainWing - relative velocity: 28.27601 - impact momentum: 101.9
[LOG 15:11:24.004] [Explosion] Combined.
[LOG 15:11:24.010] airlinerCtrlSrf Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.016] [airlinerCtrlSrf]: Deactivated
[LOG 15:11:24.026] [F: 47718]: airlinerMainWing collided into turboFanSize2 - relative velocity: 20.57582 - impact momentum: 92.9
[LOG 15:11:24.030] [Explosion] Combined.
[LOG 15:11:24.034] airlinerMainWing Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.063] [airlinerMainWing]: Deactivated
[LOG 15:11:24.069] [F: 47718]: elevon5 collided into mk3CargoBayM - relative velocity: 17.83668 - impact momentum: 53.5
[LOG 15:11:24.073] [Explosion] Combined.
[LOG 15:11:24.078] elevon5 Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.082] [elevon5]: Deactivated
[LOG 15:11:24.088] [F: 47718]: deltaWing collided into mk3CargoBayM - relative velocity: 28.66253 - impact momentum: 86.0
[LOG 15:11:24.093] [Explosion] Combined.
[LOG 15:11:24.097] deltaWing Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.101] [deltaWing]: Deactivated
[LOG 15:11:24.106] [F: 47718]: wingShuttleDelta collided into mk3CargoBayM - relative velocity: 29.34482 - impact momentum: 88.0
[LOG 15:11:24.110] [Explosion] Combined.
[LOG 15:11:24.113] wingShuttleDelta Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.129] [wingShuttleDelta]: Deactivated
[EXC 15:11:24.135] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:24.137] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:24.138] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[LOG 15:11:24.140] [F: 47718]: wingConnector2 collided into mk3CargoBayM - relative velocity: 34.04583 - impact momentum: 102.1
[LOG 15:11:24.144] [Explosion] Combined.
[LOG 15:11:24.149] wingConnector2 Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.155] [strutConnector]: Deactivated
[LOG 15:11:24.162] [wingConnector2]: Deactivated
[LOG 15:11:24.168] [F: 47718]: wingShuttleDelta collided into mk3CargoBayM - relative velocity: 29.01835 - impact momentum: 87.1
[LOG 15:11:24.172] [Explosion] Combined.
[LOG 15:11:24.177] wingShuttleDelta Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.183] [wingShuttleDelta]: Deactivated
[LOG 15:11:24.189] [F: 47718]: deltaWing collided into mk3CargoBayM - relative velocity: 28.9845 - impact momentum: 87.0
[LOG 15:11:24.193] [Explosion] Combined.
[LOG 15:11:24.197] deltaWing Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.206] [deltaWing]: Deactivated
[LOG 15:11:24.211] [F: 47718]: airlinerCtrlSrf collided into mk3CargoBayM - relative velocity: 16.70443 - impact momentum: 50.1
[LOG 15:11:24.215] [Explosion] Combined.
[LOG 15:11:24.219] airlinerCtrlSrf Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.224] [airlinerCtrlSrf]: Deactivated
[LOG 15:11:24.231] [F: 47718]: wingConnector2 collided into mk3CargoBayM - relative velocity: 26.19898 - impact momentum: 78.6
[LOG 15:11:24.235] [Explosion] Combined.
[LOG 15:11:24.241] wingConnector2 Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.256] [strutConnector]: Deactivated
[LOG 15:11:24.265] [wingConnector2]: Deactivated
[LOG 15:11:24.271] [F: 47718]: wingStrake collided into mk3CargoBayM - relative velocity: 44.40771 - impact momentum: 133.2
[LOG 15:11:24.275] [Explosion] Combined.
[LOG 15:11:24.280] wingStrake Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.284] [wingStrake]: Deactivated
[EXC 15:11:24.290] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[LOG 15:11:24.292] [F: 47718]: wingConnector2 collided into mk3CargoBayM - relative velocity: 30.577 - impact momentum: 91.7
[LOG 15:11:24.298] [Explosion] Combined.
[LOG 15:11:24.303] wingConnector2 Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.307] [wingConnector2]: Deactivated
[EXC 15:11:24.313] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:24.314] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[LOG 15:11:24.316] [F: 47718]: wingConnector2 collided into mk3CargoBayM - relative velocity: 21.82494 - impact momentum: 65.5
[LOG 15:11:24.321] [Explosion] Combined.
[LOG 15:11:24.326] wingConnector2 Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.334] [strutConnector]: Deactivated
[LOG 15:11:24.340] [wingConnector2]: Deactivated
[EXC 15:11:24.396] NullReferenceException: Object reference not set to an instance of an object
	ProtoPartSnapshot.Load (.Vessel vesselRef, Boolean loadAsRootPart)
	ProtoVessel.LoadObjects ()
	Vessel.Load ()
	Vessel.Update ()
[EXC 15:11:24.401] NullReferenceException: Object reference not set to an instance of an object
	Part.GetModuleStartState ()
	Part.ModulesOnStart ()
	Part+<Start>c__Iterator38.MoveNext ()
	UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
[LOG 15:11:24.418] 1 explosions created.
[EXC 15:11:24.449] NullReferenceException: Object reference not set to an instance of an object
	ModuleAnimateGeneric.FixedUpdate ()
[EXC 15:11:24.451] NullReferenceException: Object reference not set to an instance of an object
	ModuleAnimateGeneric.FixedUpdate ()
[EXC 15:11:24.462] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:24.465] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[LOG 15:11:24.467] [F: 47719]: airlinerMainWing collided into turboFanSize2 - relative velocity: 16.32361 - impact momentum: 73.6
[LOG 15:11:24.471] airlinerMainWing Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.490] [airlinerMainWing]: Deactivated
[LOG 15:11:24.496] [F: 47719]: wingConnector2 collided into turboFanSize2 - relative velocity: 19.93002 - impact momentum: 90.0
[LOG 15:11:24.501] wingConnector2 Exploded!! - blast awesomeness: 0.1
[LOG 15:11:24.505] [wingConnector2]: Deactivated
[EXC 15:11:24.512] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionExit (UnityEngine.Collision c)
[EXC 15:11:24.513] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionStay (UnityEngine.Collision c)
[EXC 15:11:24.514] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionStay (UnityEngine.Collision c)
[EXC 15:11:24.516] NullReferenceException: Object reference not set to an instance of an object
	Part.OnCollisionStay (UnityEngine.Collision c)

**Comment by RacerXx** [comment]
For comparision with Lothsahn we were in same session
[Rednecks_KSP_log .txt](https://github.com/DaggerES/LunaMultiPlayer/files/574077/Rednecks_KSP_log.txt)

**Comment by Lothsahn** [comment]
This issue is likely fixed in the latest commit, but we'll need to retest
