### ISSUE TITLE
Client can't be found in game

### ISSUE THREAD

**Issue by hyx5020** [DaggerES/LunaMultiPlayer#32]
OS: Windows 10 Insider Preview

KSPVersion: 1.3.0.1804 (WindowsPlayer x64) zh-cn

#### Steps to reproduce: Follow Readme-how to build LMP
![qq 20170708192511](https://user-images.githubusercontent.com/21760321/27984871-47bd4f1e-6413-11e7-8a0b-a3a9a6d8e76a.png)

**Comment by RacerXx** [comment]
did you compile the client correctly?

**Comment by hyx5020** [comment]
The client's build is successful, and VS does not have any error. After switching to English still can not see anything about LMP. I can't find any error information about LMP, this is my KSP.log
[http://211server-virginia.oss-us-east-1.aliyuncs.com/KSP.log](url)

**Comment by DaggerES** [comment]
I'm a bit away of LMP (hope to pick it back up soon) but could it be that the popup is outside of the screen?

The log seems right...

**Comment by hyx5020** [comment]
I'm not sure because my resolution is up to 1920 * 1080, I have no way to determine the higher resolution of the situation..

**Comment by hyx5020** [comment]
Find the problem, after the completion of the VS build, client's DisclaimerAccepted default to false, changed to true to show the client
 <DisclaimerAccepted>false</DisclaimerAccepted>

**Comment by DaggerES** [comment]
Then probably it's a bug because that disclaimer is not being shown....
