### ISSUE TITLE
Kerbals die over and over

### ISSUE THREAD

**Issue by Lothsahn** [DaggerES/LunaMultiPlayer#9]
![image](https://cloud.githubusercontent.com/assets/10092359/19833535/700ea0e8-9e12-11e6-86d8-e96c7731fc57.png)

This was in my log from the mission.  Also, we were seeing some pretty heavy lag--not sure if it was related.  2 people were in a game and we did recover some ships prior to this flight.

**Comment by DaggerES** [comment]
Couldn't reproduce it locally. I'd need log or detailed steps

**Comment by Lothsahn** [comment]
Can't reproduce.
